Models/ProductImage.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ComicBookStore.Models
{
    public class ProductImage
    {
        public int ID { get; set; }

        [Required]
        [Display(Name = "ProductID")]
        public int ProductID { get; set; }

        [Required]
        [Display(Name = "File Name")]
        public string ImageFileName { get; set; }

        [NotMapped]
        public string ImageUrl { get; set; }

        [Required]
        [Display(Name = "Is Feature")]
        public bool IsFeature { get; set; }

        [Required]
        [Display(Name = "Created At")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime CreatedAt { get; set; }

        [Display(Name = "Updated At")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime UpdatedAt { get; set; }
    }
}

Models/ViewModels/ProductImageViewModel.cs
using ComicBookStore.Repositories.DTO;
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ComicBookStore.Models.ViewModels
{
    public class ImageUrlWithID
    {
        public int ID { get; set; }
        public string URL { get; set; }
        public string FileName { get; set; }
    }


    public class ProductImageViewModel
    {
        public ProductDTO ProductDTO { get; set; }
        public int ProductID { get; set; }
        public List<string> ProductImagesURL { get; set; }
        public List<ImageUrlWithID> ImageUrlWithID { get; set; }
        public IFormFile FileUpload { get; set; }
    }
}

Controllers/ProductImagesController.cs
using ComicBookStore.Data;
using ComicBookStore.Models;
using ComicBookStore.Models.ViewModels;
using ComicBookStore.Services;
using ComicBookStore.Utility;
using Firebase.Auth;
using Firebase.Storage;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace ComicBookStore.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ProductImagesController : Controller
    {
        public readonly IWebHostEnvironment _environment;
        public readonly ProductsService _productsService;
        public readonly ApplicationDbContext _db;

        public ProductImagesController(
            IWebHostEnvironment environment, 
            ProductsService productsService,
            ApplicationDbContext db)
        {
            _environment = environment;
            _productsService = productsService;
            _db = db;
        }

        public async Task<IActionResult> Index()
        {
            var products = (await _productsService.GetProductDetailDTO()).Value;

            return View(products);
        }

        public async Task<IActionResult> Create(int id)
        {
            var product = (await _productsService.GetByIdProductDetailDTO(id)).Value;

            if (product == null) return NotFound();

            var auth = new FirebaseAuthProvider(new FirebaseConfig(FirebaseKeys.ApiKey));
            var a = await auth.SignInWithEmailAndPasswordAsync(FirebaseKeys.AuthEmail, FirebaseKeys.AuthPassword);

            List<string> productImagesURL = new List<string>();
            foreach (var item in product.ProductImages)
            {
                var task = new FirebaseStorage(
                    FirebaseKeys.Bucket,
                    new FirebaseStorageOptions
                    {
                        AuthTokenAsyncFactory = () => Task.FromResult(a.FirebaseToken),
                        ThrowOnCancel = true
                    })
                    .Child("images")
                    .Child($"{item.ImageFileName}")
                    .GetDownloadUrlAsync().Result;

                productImagesURL.Add(task);
            }

            ProductImageViewModel productImageViewModel = new ProductImageViewModel()
            {
                ProductDTO = product,
                ProductID = product.ID,
                ProductImagesURL = productImagesURL
            };

            return View(productImageViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProductID,FileUpload")] ProductImageViewModel productImageViewModel)
        {

            FileStream fs;
            var fileUpload = productImageViewModel.FileUpload;
            var folderName = "firebase";
            var productID = productImageViewModel.ProductID;
            string fileName = Guid.NewGuid() + "_" + fileUpload.FileName;
            string filePath = Path.Combine(_environment.WebRootPath, $"images/{folderName}", fileName);
            string fileImagePath = Path.Combine(_environment.ContentRootPath, "wwwroot/images/firebase/", fileName);

            if (ModelState.IsValid && fileUpload.Length > 0)
            {
                // upload file to static image
                using (var fileStream = new FileStream(fileImagePath, FileMode.Create))
                {
                    await fileUpload.CopyToAsync(fileStream);
                }

                // Upload static image to firebase
                fs = new FileStream(filePath, FileMode.Open);
                var auth = new FirebaseAuthProvider(new FirebaseConfig(FirebaseKeys.ApiKey));
                var a = await auth.SignInWithEmailAndPasswordAsync(FirebaseKeys.AuthEmail, FirebaseKeys.AuthPassword);
                var cancellation = new CancellationTokenSource();

                var upload = new FirebaseStorage(
                    FirebaseKeys.Bucket,
                    new FirebaseStorageOptions
                    {
                        AuthTokenAsyncFactory = () => Task.FromResult(a.FirebaseToken),
                        ThrowOnCancel = true
                    })
                    .Child("images")
                    .Child($"{fileName}")
                    .PutAsync(fs, cancellation.Token);

                await upload;

                ProductImage productImage = new ProductImage()
                {
                    ProductID = productID,
                    ImageFileName = fileName,
                    IsFeature = false,
                    CreatedAt = DateTime.Now,
                    UpdatedAt = DateTime.Now
                };

                _db.Add(productImage);
                await _db.SaveChangesAsync();

                fs.Close();
                System.IO.File.Delete(filePath);

                return RedirectToAction(nameof(Index));
            }

            return BadRequest();
        }

        public async Task<IActionResult> Edit(int id)
        {
            var product = (await _productsService.GetByIdProductDetailDTO(id)).Value;

            if (product == null) return NotFound();

            var auth = new FirebaseAuthProvider(new FirebaseConfig(FirebaseKeys.ApiKey));
            var a = await auth.SignInWithEmailAndPasswordAsync(FirebaseKeys.AuthEmail, FirebaseKeys.AuthPassword);

            var productImagesURL = new List<ImageUrlWithID>();
            foreach (var item in product.ProductImages)
            {
                var task = new FirebaseStorage(
                    FirebaseKeys.Bucket,
                    new FirebaseStorageOptions
                    {
                        AuthTokenAsyncFactory = () => Task.FromResult(a.FirebaseToken),
                        ThrowOnCancel = true
                    })
                    .Child("images")
                    .Child($"{item.ImageFileName}")
                    .GetDownloadUrlAsync().Result;

                var productImage = new ImageUrlWithID()
                {
                    ID = item.ID,
                    URL = task,
                    FileName = item.ImageFileName
                };

                productImagesURL.Add(productImage);
            }

            ProductImageViewModel productImageViewModel = new ProductImageViewModel()
            {
                ProductDTO = product,
                ProductID = product.ID,
                ImageUrlWithID = productImagesURL
            };

            return View(productImageViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<List<int>> Delete(List<int> productImageIds)
        {
            var productImages = await _db.ProductImages
                .Where(p => productImageIds.Contains(p.ID))
                .ToListAsync();

            var auth = new FirebaseAuthProvider(new FirebaseConfig(FirebaseKeys.ApiKey));
            var a = await auth.SignInWithEmailAndPasswordAsync(FirebaseKeys.AuthEmail, FirebaseKeys.AuthPassword);

            foreach (var item in productImages)
            {
                var delete = new FirebaseStorage(
                    FirebaseKeys.Bucket,
                    new FirebaseStorageOptions
                    {
                        AuthTokenAsyncFactory = () => Task.FromResult(a.FirebaseToken),
                        ThrowOnCancel = true
                    })
                    .Child("images")
                    .Child($"{item.ImageFileName}")
                    .DeleteAsync();

                await delete;
            }

            _db.ProductImages.RemoveRange(productImages);
            await _db.SaveChangesAsync();
          

            return productImageIds;
        }
    }
}

Views/ProductImages/Create.cshtml
@model ComicBookStore.Models.ViewModels.ProductImageViewModel
@{
    ViewData["Title"] = "Create";
}

<div class="text-center">
    <h1 class="display-4">Upload Image of @Model.ProductDTO.Name</h1>
</div>

<div class="border container" style="padding: 30px">
    <form asp-action="Create" enctype="multipart/form-data">
        <div class="text-danger" asp-validation-summary="ModelOnly"></div>

        <input type="hidden" asp-for="ProductID" value="@Model.ProductDTO.ID" />
        <div class="form-group row">
            <div class="col-4">Image</div>
            <div class="col-6">
                <div class="custom-file">
                    <input asp-for="FileUpload" type="file" class="custom-file-input" id="customFile" />
                    <label class="custom-file-label" for="customFile">Choose file</label>
                </div>
            </div>
        </div>

        <div class="form-group row">
            <div class="offset-4 col-6">
                <input type="submit" value="Create" class="btn btn-primary form-control" />
            </div>
        </div>

    </form>
</div>

<div class="mt-5">
    <div class="row d-flex justify-content-center">
        @foreach (var URL in Model.ProductImagesURL)
        {
            <div class="col-xl-4 col-lg-4 col-md-6 col-sm-12 col-12 mt-2">
                <img src="@URL" alt="product" class="img-fluid " />
            </div>
        }
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/ProductImages/Delete.cshtml
@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

Views/ProductImages/Edit.cshtml
@model ComicBookStore.Models.ViewModels.ProductImageViewModel
@{
    ViewData["Title"] = "Edit";
}

<div class="text-center">
    <h1 class="display-4">Edit</h1>
</div>

<div class="mt-5">
    <form method="post">
        <div class="text-danger" asp-validation-summary="ModelOnly"></div>

        <div class="row d-flex justify-content-center">

            @foreach (var item in Model.ImageUrlWithID)
            {
                <div id="@item.ID" class="col-xl-4 col-lg-4 col-md-6 col-sm-12 col-12">
                    <img src="@item.URL" alt="product" class="img-fluid " />
                    <div class="form-check text-center mb-5">
                        <input class="form-check-input"
                               type="checkbox"
                               value="@item.ID">
                    </div>
                </div>
            }
        </div>

        @if (Model.ImageUrlWithID.Count == 0)
        {
            <div class="form-group row mt-5">
                <div class="offset-3 col-6 text-center">
                    No Images
                </div>
            </div>
        }
        else
        {
            <div class="form-group row mt-5">
                <div class="offset-3 col-6">
                    <input id="btnDelete" type="submit" value="Delete" class="btn btn-danger form-control" />
                </div>
            </div>
        }



    </form>
</div>

@section scripts{
    <script>
        $("input[type=checkbox]").on("click", function () {
            if ($(this).attr('checked')) {
                $(this).removeAttr('checked');
            } else {
                $(this).attr('checked', 'checked')
            }
        })

        $("#btnDelete").on("click", function () {
            event.preventDefault();

            let idArray = [];
            $("input[type = checkbox]").each(function () {
                if ($(this).attr('checked')) {
                    idArray.push($(this).val());
                }
            })

            if (idArray.length > 0) {
                var antiForgeryToken = $("input[name=__RequestVerificationToken]").val();

                $.ajax({
                    url: "/ProductImages/Delete",
                    type: "POST",
                    contentType: "application/x-www-form-urlencoded; charset=utf-8",
                    dataType: "json",
                    data: {
                        __RequestVerificationToken: antiForgeryToken,
                        productImageIds: idArray
                    },
                    success: function (result) {
                        result.forEach(function (id) {
                            console.log(id);
                            $(`#${id}`).fadeOut();
                        });
                    },
                    error: function (errorMessage) {
                        alert(errorMessage.responseText);
                    }
                })
            }
        })
    </script>
 }

Views/ProductImages/Index.cshtml
@model IEnumerable<ComicBookStore.Repositories.DTO.ProductDTO>
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ProductTypeName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsActive)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.ProductTypeName)</td>
                <td>@Html.DisplayFor(modelItem => item.Name)</td>
                <td>@Html.DisplayFor(modelItem => item.IsActive)</td>
                <td>
                    <a asp-controller="ProductImages" asp-action="Create" asp-route-id="@item.ID">Create</a> |
                    <a asp-controller="ProductImages" asp-action="Edit" asp-route-id="@item.ID">Edit</a>
                </td>
            </tr>
        }
    </tbody>

</table>