Models/ProductInventory.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ComicBookStore.Models
{
    public class ProductInventory
    {
        public int ID { get; set; }

        [Required(ErrorMessage = "Is Active is required")]
        [Display(Name = "Is Active")]
        public bool IsActive { get; set; }

        [Required(ErrorMessage = "In Stock is required")]
        [Display(Name = "In Stock")]
        public bool InStock { get; set; }

        [Required(ErrorMessage = "Created At is required")]
        [Display(Name = "Created At")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime CreatedAt { get; set; }

        [Display(Name = "Updated At")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime UpdatedAt { get; set; }

        [Display(Name = "Product")]
        [Required(ErrorMessage = "Product is required")]
        public int ProductID { get; set; }
        public Product Product { get; set; }
    }
}

Controllers/ProductInventoryController.cs
using ComicBookStore.Data;
using ComicBookStore.Models;
using ComicBookStore.Models.ViewModels;
using ComicBookStore.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ComicBookStore.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ProductInventoryController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly ProductInventoryService _productInventoryService;
        private readonly ProductsService _productsService;

        public ProductInventoryController(
            ApplicationDbContext db,
            ProductInventoryService productInventoryService, 
            ProductsService productsService)
        {
            _db = db;
            _productInventoryService = productInventoryService;
            _productsService = productsService;
        }

        public async Task<IActionResult> Index()
        {
            var productInventoryDTO = (await _productInventoryService.GetProductInventoryDTO()).Value;

            return View(productInventoryDTO);
        }

        public async Task<IActionResult> Details(int id)
        {
            var productInventoryDTO = (await _productInventoryService.GetProductInventoryByProductIdDTO(id)).Value;

            return View(productInventoryDTO);
        }

        public async Task<IActionResult> Create()
        {
            var product = (await _productsService.GetProductDTO()).Value;

            var createProductInventoryViewModel = new CreateProductInventoryViewModel()
            {
                Products = product
            };

            return View(createProductInventoryViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Quantity,ProductID,InStock,IsActive")] CreateProductInventoryViewModel model)
        {
            if (ModelState.IsValid)
            {
                var response = await _productInventoryService.PostRange(model);

                if (response.Value) return RedirectToAction(nameof(Index));
            }

            var product = (await _productsService.GetProductDTO()).Value;
            var createProductInventoryViewModel = new CreateProductInventoryViewModel()
            {
                Products = product
            };

            return View(createProductInventoryViewModel);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var inventoryItem = (await _productInventoryService.GetInventoryItemDTO(id)).Value;

            if (inventoryItem == null) return NotFound();

            var createProductInventoryViewModel = new CreateProductInventoryViewModel()
            {
                ID = inventoryItem.ID,
                InStock = inventoryItem.InStock,
                IsActive = inventoryItem.IsActive,
                CreatedAt = inventoryItem.CreatedAt,
                UpdatedAt = inventoryItem.UpdatedAt,
                ProductID = inventoryItem.ProductID
            };

            return View(createProductInventoryViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Quantity,IsActive,InStock,CreatedAt,UpdatedAt,ProductID")] CreateProductInventoryViewModel model)
        {
            if (id != model.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _productInventoryService.Edit(model);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductInventoryExists(model.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Details), new { id = model.ProductID });
            }
            return View(model);
        }

        // GET: ProductInventory/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var productInventory = (await _productInventoryService.GetInventoryItemDTO(id)).Value;

            if (productInventory == null)
            {
                return NotFound();
            }

            return View(productInventory);
        }

        // POST: ProductInventory/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _productInventoryService.Delete(id);
            return RedirectToAction(nameof(Index));
        }

        private bool ProductInventoryExists(int id)
        {
            return _db.ProductInventory.Any(e => e.ID == id);
        }
    }
}

Views/ProductInventory/Create.cshtml
@model ComicBookStore.Models.ViewModels.CreateProductInventoryViewModel
@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Product Inventory</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="ProductID" class="control-label"></label>
                <select class="form-select form-control" aria-label="Product ID" asp-for="ProductID">
                    <option value="" selected>Select Product</option>
                    @foreach (var item in Model.Products)
                    {
                        <option value="@item.ID">@item.Name</option>
                    }
                </select>
                <span asp-validation-for="ProductID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="InStock" class="control-label"></label>
                <input asp-for="InStock" class="form-control" />
                <span asp-validation-for="InStock" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IsActive" class="control-label"></label>
                <input asp-for="IsActive" class="form-control" />
                <span asp-validation-for="IsActive" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

Views/ProductInventory/Delete.cshtml
@model ComicBookStore.Repositories.DTO.InventoryItemDTO
@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<hr />
<div>
    <h4>Product Inventory @Html.DisplayFor(model => model.ID)</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.InStock)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.InStock)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IsActive)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UpdatedAt)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UpdatedAt)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a asp-action="Details" asp-route-id="@Model.ProductID">Back to List</a>
    </form>
</div>

Views/ProductInventory/Details.cshtml
@model ComicBookStore.Repositories.DTO.ProductInventoryDTO
@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<h4>@Html.DisplayFor(model => model.ProductName) - Inventory</h4>
<hr />

<table class="table">
    <thead>
        <tr class="text-center">
            <th>Active</th>
            <th>Stock</th>
            <th>Created</th>
            <th>Updated</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.ProductInventory)
        {
            <tr class="text-center">
                <td>@Html.DisplayFor(modelItem => item.IsActive)</td>
                <td>@Html.DisplayFor(modelItem => item.InStock)</td>
                <td>@Html.DisplayFor(modelItem => item.CreatedAt)</td>
                <td>@Html.DisplayFor(modelItem => item.UpdatedAt)</td>
                <td>
                    <a asp-controller="ProductInventory" asp-action="Edit" asp-route-id="@item.ID">
                        Edit
                    </a> |
                    <a asp-controller="ProductInventory" asp-action="Delete" asp-route-id="@item.ID">
                        Delete
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/ProductInventory/Edit.cshtml
@model ComicBookStore.Models.ViewModels.CreateProductInventoryViewModel
@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Product Inventory</h4>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <input type="hidden" asp-for="ID" value="@Model.ID" />
            <input type="hidden" asp-for="ProductID" value="@Model.ProductID" />
            <input type="hidden" asp-for="CreatedAt" value="@Model.CreatedAt" />
            <input type="hidden" asp-for="UpdatedAt" value="@Model.UpdatedAt" />
            <input type="hidden" asp-for="Quantity" value="1" />

            <div class="form-group">
                <label asp-for="InStock" class="control-label"></label>
                <input asp-for="InStock" class="form-control" />
                <span asp-validation-for="InStock" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="IsActive" class="control-label"></label>
                <input asp-for="IsActive" class="form-control" />
                <span asp-validation-for="IsActive" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>

        </form>
    </div>
</div>

Views/ProductInventory/Index.cshtml
@model IEnumerable<ComicBookStore.Repositories.DTO.ProductInventoryDTO>
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-controller="ProductInventory" asp-action="Create">Create</a>
</p>

<table class="table">
    <thead>
        <tr class="text-center">
            <th>
                @Html.DisplayNameFor(model => model.ProductCategoryName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProductTypeName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProductName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProductIsActive)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProductInventory)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr class="text-center">
                <td>@Html.DisplayFor(modelItem => item.ProductCategoryName)</td>
                <td>@Html.DisplayFor(modelItem => item.ProductTypeName)</td>
                <td>@Html.DisplayFor(modelItem => item.ProductName)</td>
                <td>@Html.DisplayFor(modelItem => item.ProductIsActive)</td>
                <td>
                    <a asp-controller="ProductInventory" asp-action="Details" asp-route-id="@item.ID">
                        @item.ProductInventory.Count()
                    </a>
                </td>
            </tr>
        }
    </tbody>
    
</table>