Models/ProductSpecification.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ComicBookStore.Models
{
    public class ProductSpecification
    {
        public int ID { get; set; }

        [Required]
        [StringLength(128, ErrorMessage = "{0} can have a maximum of {1} characters")]
        [Display(Name = "Name")]
        public string Name { get; set; }

        [Required]
        public int ProductTypeID { get; set; }
        public ProductType ProductType { get; set; }

        public ICollection<ProductSpecificationValue> ProductSpecificationValues { get; set; }

    }
}

Controllers/ProductSpecificationsController.cs
using ComicBookStore.Models;
using ComicBookStore.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ComicBookStore.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ProductSpecificationsController : Controller
    {
        private readonly ProductsService _productsService;
        private readonly ProductTypeService _productTypeService;
        private readonly ProductSpecificationService _productSpecificationService;
        private readonly ProductSpecificationValueService _productSpecificationValueService;

        public ProductSpecificationsController(
            ProductsService productsService,
            ProductTypeService productTypeService, 
            ProductSpecificationService productSpecificationService,
            ProductSpecificationValueService productSpecificationValueService)
        {
            _productsService = productsService;
            _productTypeService = productTypeService;
            _productSpecificationService = productSpecificationService;
            _productSpecificationValueService = productSpecificationValueService;
        }

        public async Task<IActionResult> Index()
        {
            var productTypes = (await _productTypeService.GetProductTypeWithProductSpecificationsDTO()).Value;

            return View(productTypes);
        }

        public async Task<IActionResult> Create(int id)
        {
            var productType = (await _productTypeService.GetByIdProductTypeWithProductSpecificationsDTO(id)).Value;

            return View(productType);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(
            int id, 
            [Bind("ProductSpecification")] IList<ProductSpecification> productSpecification)
        {
            if (ModelState.IsValid)
            {
                // Creates the new productSpecifications
                var productSpecifications = (await _productSpecificationService.PostProductSpecificationRange(productSpecification)).Value;

                // Finds all products that match productTypeID
                var products = (await _productsService.GetProductDTOByProductTypeID(id: id)).Value;

                // Creates new productSpecificationValues for the current products in the database
                var productSpecificationValues = _productSpecificationService.CreateProductSpecificationValueList(productSpecifications, products);

                // Adds the new productSpecificationValues in the database
                var response = (await _productSpecificationValueService.PostRange(productSpecificationValues)).Value;

                if (response) return RedirectToAction(nameof(Create), new { id = id });
            }

            var productType = (await _productTypeService.GetByIdProductTypeWithProductSpecificationsDTO(id)).Value;

            return View(productType);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var productType = (await _productTypeService.GetByIdProductTypeWithProductSpecificationsDTO(id)).Value;

            return View(productType);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(
            int id,
            [Bind("ProductSpecification")] IList<ProductSpecification> productSpecification)
        {
            if (ModelState.IsValid)
            {
                var response = (await _productSpecificationService.EditProductSpecificationsRange(productSpecification)).Value;

                if (response != null) return RedirectToAction(nameof(Index));
            }

            var productType = (await _productTypeService.GetByIdProductTypeWithProductSpecificationsDTO(id)).Value;

            return View(productType);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var productType = (await _productTypeService.GetByIdProductTypeWithProductSpecificationsDTO(id)).Value;

            return View(productType);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult<int>> DeleteAction(int id)
        {
            // Delete ProductSpecificationValue List
            var productSpecificationValue = (await _productSpecificationValueService.DeleteByProductSpecificationID(id)).Value;

            // Delete ProductSpecification
            var productSpecification = (await _productSpecificationService.DeleteProductSpecificationByID(id)).Value;

            if (productSpecification == true && productSpecificationValue == true)
            {
                return id;
            }

            return NotFound();
        }
    }
}

Views/ProductSpecifications/Create.cshtml
@model ComicBookStore.Repositories.DTO.ProductTypeWithProductSpecificationsDTO
@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>
<br />

<div>
    <h4>Current Product Specifications</h4>
    <hr />
    <dl class="row">
        @foreach (var item in Model.ProductSpecifications)
        {
            <dt class="col-sm-4">
                - @item.Name
            </dt>
            <dd class="col-sm-8">
               
            </dd>

        }

    </dl>
</div>

<div class="row">
    <div class="col-md-4 mb-2">
        <button id="add-product-specification" class="btn btn-primary">Add</button>
        <button id="remove-product-specification" class="btn btn-danger">Remove</button>
    </div>

    
</div>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div id="append-production-specification" data-myValue="@Model.ProductTypeID"></div>

            <div id="create-product-specification" class="form-group" style="display: none;">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
        $(document).ready(function () {

            // Add Product Specification form-group
            let i = 0;
            $('#add-product-specification').click(function () {

                let productTypeId = $("[id='append-production-specification']").attr("data-myValue");

                $("#append-production-specification").append(
                    `<div class="form-group new-product-specification">
                        <label class="control-label">New Product Specification</label>
                        <input type="text" id="ProductSpecification_${i}__Value" name="ProductSpecification[${i}].Name" class="form-control" />
                        <input type="hidden" id="ProductSpecification_${i}__Value" name="ProductSpecification[${i}].ProductTypeID" value="${productTypeId}" />
                    </div>`
                ).slideDown();
                i += 1;

                showCreate();
            });

            // Remove Product Specification form-group
            $('#remove-product-specification').click(function () {
                $('#append-production-specification .form-group:last').remove();

                showCreate();
            });

            // show/hide the create button
            function showCreate() {
                let length = $(".new-product-specification").length;
                console.log(length);

                if (length === 0) {
                    $('#create-product-specification').fadeOut();
                } else {
                    $('#create-product-specification').fadeIn();
                }
            }

            @*$('#create-product-specification').hide();*@
            
        });
    </script>
}

Views/ProductSpecifications/Delete.cshtml
@model ComicBookStore.Repositories.DTO.ProductTypeWithProductSpecificationsDTO
@{
    ViewData["Title"] = "Delete";
}

<h1>Delete Product Specifications</h1>
<h4>@Model.ProductTypeName</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <h6>Select Product Specification to Delete</h6>
            <div class="list-group">
                @foreach (var item in Model.ProductSpecifications)
                {
                    <button type="button" 
                            id="@item.ID" 
                            class="list-group-item list-group-item-action" 
                            onclick=@($"Delete({item.ID})")>
                                @item.Name
                    </button>
                }
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script>
        function Delete(id) {
            event.preventDefault();

            var answer = confirm("Are you sure you want to Delete?");
            if (answer) {
                var antiForgeryToken = $("input[name=__RequestVerificationToken]").val();

                $.ajax({
                    url: "/ProductSpecifications/DeleteAction/" + id,
                    type: "POST",
                    contentType: "application/x-www-form-urlencoded; charset=utf-8",
                    dataType: "json",
                    data: {
                        __RequestVerificationToken: antiForgeryToken
                    },
                    success: function (result) {
                        $(`#${result}`).fadeOut();
                    },
                    error: function (errorMessage) {
                        alert(errorMessage.responseText);
                    }
                });
            }
        }
    </script>
}

Views/ProductSpecifications/Edit.cshtml
@model ComicBookStore.Repositories.DTO.ProductTypeWithProductSpecificationsDTO
@{
    ViewData["Title"] = "Edit";

    int count = 0;
}

<h1>Edit @Model.ProductTypeName</h1>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            @for (int i = 0; i < Model.ProductSpecifications.Count(); i++)
            {
                <div class="form-group">
                    <input type="text"
                           id=@($"ProductSpecification_{i}__Value")
                           name=@($"ProductSpecification[{i}].Name")
                           value="@Model.ProductSpecifications.ToList()[i].Name"
                           class="form-control" />
                    <input type="hidden"
                           id=@($"ProductSpecification_{i}__Value")
                           name=@($"ProductSpecification[{i}].ProductTypeID")
                           value="@Model.ProductTypeID" ) />
                    <input type="hidden"
                           id=@($"ProductSpecification_{i}__Value")
                           name=@($"ProductSpecification[{i}].ID")
                           value="@Model.ProductSpecifications.ToList()[i].ID" />
                </div>
            }

            <div class="form-group">
                <input type="submit" value="Edit" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/ProductSpecifications/Index.cshtml
@model IEnumerable<ComicBookStore.Repositories.DTO.ProductTypeWithProductSpecificationsDTO>
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<table class="table">
    <thead>
        <tr class="text-center">
            <th>
                @Html.DisplayNameFor(model => model.ProductTypeName)
            </th>
            <th>
                Product Specifications
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr class="text-center">
                <td>@Html.DisplayFor(modelItem => item.ProductTypeName)</td>
                <td>@item.ProductSpecifications.Count()</td>
                <td>
                    <a asp-controller="ProductSpecifications" asp-action="Create" asp-route-id="@item.ProductTypeID">
                        Create
                    </a> |
                    <a asp-controller="ProductSpecifications" asp-action="Edit" asp-route-id="@item.ProductTypeID">
                        Edit
                    </a> |
                    <a asp-controller="ProductSpecifications" asp-action="Delete" asp-route-id="@item.ProductTypeID">
                        Delete
                    </a>
                </td>
            </tr>
        }
    </tbody>
    
</table>